spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://db:5432/nexxclinic}
    username: ${DB_USER:nexxclinic_user}
    password: ${DB_PASSWORD:nexxclinic_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO