version: "3.9"

services:
  app:
    image: genoyves/nexclinic:latest
    container_name: nexxclinic-app
    restart: unless-stopped

    ports:
      - "8091:8080"

    environment:
      SPRING_PROFILES_ACTIVE: prod

      # IMPORTANT FIX
      DB_URL: jdbc:postgresql://host.docker.internal:5432/postgres
      DB_USER: postgres.your-tenant-id
      DB_PASSWORD: 1232c554c17bfeb7afd394af9b655ced
      DB_DRIVER: org.postgresql.Driver

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SUPABASE_URL: http://host.docker.internal:8000
      SUPABASE_SERVICE_KEY: YOUR_SERVICE_ROLE_KEY

      JWT_SECRET: your-super-secret-jwt-key-at-least-32-chars-long

    extra_hosts:
      - "host.docker.internal:host-gateway"