-- ============================================================================
-- V1: Baseline schema (generated from the JPA entities with the PostgreSQL
-- dialect via jakarta.persistence.schema-generation.scripts, Hibernate 7.2.7).
--
-- Applied automatically on FRESH databases. Existing databases (previously
-- managed by Hibernate ddl-auto=update) are baselined at version 1 by
-- spring.flyway.baseline-on-migrate and only V2+ run there.
--
-- IMPORTANT: never edit this file on an existing database after it has been
-- baselined (Flyway checksum mismatch). Add new changes as V(N+1) migrations.
-- ============================================================================

create table admin_audit_logs (created_at timestamp(6) not null, admin_user_id uuid not null, id uuid not null, target_user_id uuid not null, action_type varchar(60) not null, details TEXT, primary key (id));
create table clinic_profile_contacts (contact_order integer not null, clinic_profile_id uuid not null, contact_type varchar(32) not null check ((contact_type in ('PHONE','EMAIL','POBOX'))), contact_value varchar(200) not null, description varchar(200), primary key (contact_order, clinic_profile_id));
create table clinic_profile_metadata (metadata_order integer not null, clinic_profile_id uuid not null, meta_key varchar(255), meta_value varchar(255), primary key (metadata_order, clinic_profile_id));
create table clinic_profiles (created_at timestamp(6) not null, updated_at timestamp(6) not null, id uuid not null, tin_number varchar(128), address varchar(1024), logo_url varchar(1024), name varchar(255), username varchar(255), primary key (id));
create table consultation_answers (created_at timestamp(6) not null, submitted_at timestamp(6), updated_at timestamp(6) not null, consultation_id uuid not null, department_form_id uuid not null, department_id uuid not null, id uuid not null, patient_id uuid not null, status varchar(16) not null check ((status in ('DRAFT','FINAL','SUBMITTED'))), submitted_by_worker_id uuid, visit_id uuid not null, form_schema_version varchar(50) not null, answers TEXT not null, primary key (id), constraint uk_consultation_form_version unique (consultation_id, department_form_id, form_schema_version));
create table department_form_versions (created_at timestamp(6) not null, updated_at timestamp(6) not null, form_id uuid not null, id uuid not null, status varchar(16) not null check ((status in ('DRAFT','FINAL'))), version_number varchar(50) not null, title varchar(500) not null, description TEXT, form_data TEXT not null, primary key (id), constraint uk_department_form_version unique (form_id, version_number));
create table department_forms (created_at timestamp(6) not null, updated_at timestamp(6) not null, department_id uuid, id uuid not null, status varchar(16) not null check ((status in ('DRAFT','FINAL'))), current_version_number varchar(50) not null, title varchar(500) not null, description TEXT, form_data TEXT not null, primary key (id));
create table department_insurance_policies (created_at timestamp(6) not null, updated_at timestamp(6) not null, department_id uuid not null, id uuid not null, insurance_provider_id uuid not null, primary key (id), constraint uk_department_insurance_policy unique (department_id, insurance_provider_id));
create table department_profile_products (created_at timestamp(6) not null, updated_at timestamp(6) not null, id uuid not null, product_id uuid not null, profile_id uuid not null, primary key (id), constraint uk_department_profile_product unique (profile_id, product_id));
create table department_profiles (is_default boolean not null, created_at timestamp(6) not null, updated_at timestamp(6) not null, department_id uuid not null, id uuid not null, name varchar(150) not null, primary key (id), constraint uk_department_profile_name unique (department_id, name));
create table department_standalone_forms (is_default boolean not null, added_at timestamp(6) not null, department_id uuid not null, id uuid not null, standalone_form_id uuid not null, primary key (id), unique (department_id, standalone_form_id));
create table departments (nursing boolean not null, requests_products boolean default true, support_requests boolean not null, created_at timestamp(6) not null, updated_at timestamp(6) not null, id uuid not null, insurance_policy_mode varchar(20) not null check ((insurance_policy_mode in ('ALL','ONLY','EXCEPT'))), name varchar(150) not null unique, primary key (id));
create table form_answers (score numeric(19,4), created_at timestamp(6) not null, submitted_at timestamp(6), updated_at timestamp(6) not null, form_version_id uuid not null, id uuid not null, submitted_by uuid, status varchar(255) not null check ((status in ('DRAFT','FINAL','SUBMITTED'))), answers jsonb not null, primary key (id));
create table form_versions (major_version integer not null, minor_version integer not null, created_at timestamp(6) not null, form_id uuid not null, id uuid not null, status varchar(255) not null check ((status in ('DRAFT','FINAL'))), version_label varchar(255) not null, blocks jsonb not null, theme jsonb, primary key (id), unique (form_id, major_version, minor_version));
create table forms (is_deleted boolean not null, is_template boolean not null, created_at timestamp(6) not null, updated_at timestamp(6) not null, created_by uuid, id uuid not null, category varchar(255), description TEXT, name varchar(255) not null, type varchar(255) not null, primary key (id));
create table insurance_providers (default_coverage_percentage integer not null, supported_by_clinic boolean not null, created_at timestamp(6) not null, updated_at timestamp(6) not null, id uuid not null, acronym varchar(255) unique, icon_url varchar(255), insurance_name varchar(255) not null unique, primary key (id));
create table note_target_users (note_id uuid not null, worker_id uuid not null);
create table password_history (created_at timestamp(6) not null, id uuid not null, worker_id uuid not null, password_hash varchar(120) not null, primary key (id));
create table patient_insurances (principal_member boolean not null, valid_from date not null, valid_until date not null, created_at timestamp(6) not null, updated_at timestamp(6) not null, id uuid not null, insurance_provider_id uuid not null, patient_id uuid not null, insurance_card_number varchar(255) not null, principal_member_name varchar(255), principal_member_phone_number varchar(255), providing_company_or_employer varchar(255), primary key (id));
create table patients (date_of_birth date not null, created_at timestamp(6) not null, updated_at timestamp(6) not null, id uuid not null, patient_identifier varchar(20) not null unique, alternative_phone varchar(255), cell varchar(255), city varchar(255), district varchar(255), emergency_contact_name varchar(255), emergency_contact_phone_number varchar(255), emergency_contact_relationship varchar(255), first_name varchar(255) not null, full_name varchar(255) not null, gender varchar(255) not null check ((gender in ('MALE','FEMALE','OTHER'))), last_name varchar(255), middle_name varchar(255), national_id_number varchar(255) unique, passport_number varchar(255) unique, postal_address varchar(255), primary_phone_number varchar(255), village varchar(255), primary key (id));
create table product_coverage_authorization_reasons (coverage_id uuid not null, reason varchar(120) not null);
create table product_insurance_coverages (cost numeric(19,2) not null, covered boolean not null, require_medical_advisor boolean not null, created_at timestamp(6) not null, updated_at timestamp(6) not null, id uuid not null, insurance_provider_id uuid not null, product_id uuid not null, drug_administration_frequency varchar(32) not null check ((drug_administration_frequency in ('CUSTOM_HOURS'))), must_prescribed_by varchar(32) not null check ((must_prescribed_by in ('ALL'))), primary key (id), constraint uk_product_coverage_provider unique (product_id, insurance_provider_id));
create table products (clinic_price numeric(19,2), private_rhic_price numeric(19,2), created_at timestamp(6) not null, updated_at timestamp(6) not null, id uuid not null, type varchar(32) not null check ((type in ('DRUG','MEDICAL_ACT','BIOLOGICAL_ACT','CONSUMABLE_DEVICE'))), code varchar(64) not null unique, unit varchar(64) not null check ((unit in ('TABLET','CAPSULE','PESSARY','SUPPOSITORY','BOX_OF_6_TABLETS','BOX_OF_7_PESSARIES','BOX_OF_9_TABLETS','BOX_OF_12_TABLETS','BOX_OF_12_PESSARIES','BOX_OF_14_TABLETS','BOX_OF_18_TABLETS','BOX_OF_18_PESSARIES','BOX_OF_24_TABLETS','BOX_OF_1_PESSARY','BOX_OF_3_PESSARIES','BOX_OF_6_PESSARIES','BOTTLE','VIAL','AMPOULE','TUBE','TUBE_OF_15_TABLETS','TUBE_OF_20_TABLETS','TUBE_OF_50_STRIPS','BOX','SACHET','POT','ROLL','PIECE','DOSE','KIT_OF_ONE_DAY_DOSE','PCS','UNKNOWN'))), generic_name varchar(200), name varchar(200) not null, description varchar(500), metadata oid not null, primary key (id));
create table refresh_tokens (created_at timestamp(6) not null, expires_at timestamp(6) not null, revoked_at timestamp(6), id uuid not null, replaced_by_token_id uuid, worker_id uuid not null, token_hash varchar(64) not null unique, revoke_reason varchar(100), primary key (id));
create table revoked_tokens (created_at timestamp(6) not null, expires_at timestamp(6) not null, id uuid not null, revoked_by_user_id uuid, token_id varchar(36) not null unique, reason varchar(100), primary key (id));
create table uploads (created_at timestamp(6) not null, size bigint not null, updated_at timestamp(6) not null, id uuid not null, bucket varchar(255) not null, content_type varchar(255) not null, file_name varchar(255) not null, original_file_name varchar(255) not null, storage_path varchar(255) not null, url varchar(255) unique, visibility varchar(255) not null check ((visibility in ('PUBLIC','PRIVATE'))), primary key (id));
create table visit_billing_containers (created_at timestamp(6) not null, updated_at timestamp(6) not null, billing_version_id uuid, id uuid not null, visit_id uuid not null, primary key (id));
create table visit_billing_items (insurance_covered_amount numeric(19,2) not null, line_total numeric(19,2) not null, patient_payable_amount numeric(19,2) not null, quantity_snapshot numeric(19,4) not null, unit_price_snapshot numeric(19,2) not null, created_at timestamp(6) not null, updated_at timestamp(6) not null, applied_patient_insurance_id uuid, billing_version_id uuid, department_insurance_billing_id uuid, id uuid not null, visit_department_product_id uuid not null, visit_department_product_snapshot_id uuid, primary key (id));
create table visit_billing_payments (amount numeric(19,2) not null, created_at timestamp(6) not null, updated_at timestamp(6) not null, billing_version_id uuid, id uuid not null, visit_department_billing_id uuid not null, payment_method varchar(32) not null check ((payment_method in ('CASH','MOBILE_MONEY','CARD','BANK_TRANSFER','CHEQUE','MIXED'))), reference varchar(255), primary key (id));
create table visit_billing_versions (version integer not null, created_at timestamp(6) not null, id uuid not null, supersedes_version_id uuid, visit_id uuid not null, primary key (id), unique (visit_id, version));
create table visit_billings (insurance_covered_amount numeric(19,2) not null, outstanding_amount numeric(19,2) not null, paid_amount numeric(19,2) not null, patient_payable_amount numeric(19,2) not null, total_amount numeric(19,2) not null, created_at timestamp(6) not null, updated_at timestamp(6) not null, billing_version_id uuid, id uuid not null, patient_insurance_id uuid, status varchar(16) not null check ((status in ('UNPAID','PARTIALLY_PAID','PAID'))), visit_department_billing_id uuid, invoice_url varchar(255), primary key (id));
create table visit_department_billings (insurance_covered_amount numeric(19,2) not null, outstanding_amount numeric(19,2) not null, paid_amount numeric(19,2) not null, patient_payable_amount numeric(19,2) not null, total_amount numeric(19,2) not null, created_at timestamp(6) not null, updated_at timestamp(6) not null, id uuid not null, status varchar(16) not null check ((status in ('UNPAID','PARTIALLY_PAID','PAID'))), visit_billing_id uuid not null, visit_department_id uuid not null, primary key (id));
create table visit_department_diagnostics (created_at timestamp(6) not null, updated_at timestamp(6) not null, id uuid not null, visit_department_id uuid not null, diagnosis_name varchar(255) not null, icd11_code varchar(255), primary key (id));
create table visit_department_medications (created_at timestamp(6) not null, updated_at timestamp(6) not null, id uuid not null, visit_department_id uuid not null, instructions varchar(255) not null, medication_name varchar(255) not null, primary key (id));
create table visit_department_note_viewers (viewed_at timestamp(6) not null, id uuid not null, note_id uuid not null, viewer_id uuid not null, primary key (id), constraint uk_visit_department_note_viewer unique (note_id, viewer_id));
create table visit_department_notes (note_type smallint not null check ((note_type in (0,1,2,3,4))), created_at timestamp(6) not null, updated_at timestamp(6) not null, created_by_id uuid, id uuid not null, visit_department_id uuid not null, content TEXT not null, primary key (id));
create table visit_department_processors (visit_department_id uuid not null, worker_id uuid not null);
create table visit_department_product_snapshots (quantity numeric(19,4) not null, unit_price numeric(19,2) not null, created_at timestamp(6) not null, added_by_worker_id uuid, applied_patient_insurance_id uuid, billed_by_worker_id uuid, billing_version_id uuid not null, id uuid not null, product_id uuid not null, status varchar(16) not null check ((status in ('BILLED','EXEMPTED','CORRECTION_PENDING','UNPAID','PENDING'))), visit_department_id uuid not null, visit_department_product_id uuid not null, primary key (id));
create table visit_department_products (deleted boolean not null, price numeric(19,2) not null, quantity numeric(19,4) not null, created_at timestamp(6) not null, updated_at timestamp(6) not null, added_by_worker_id uuid, billed_by_worker_id uuid, id uuid not null, processor_worker_id uuid, product_id uuid not null, source varchar(16) not null check ((source in ('USER','PROFILE'))), status varchar(16) not null check ((status in ('BILLED','EXEMPTED','CORRECTION_PENDING','UNPAID','PENDING'))), visit_department_id uuid not null, primary key (id));
create table visit_departments (completed_at timestamp(6), created_at timestamp(6) not null, updated_at timestamp(6) not null, answer_id uuid, department_id uuid not null, id uuid not null, parent_visit_department_id uuid, profile_id uuid, visit_id uuid not null, encounter_type varchar(255) default 'OUTPATIENT' not null check ((encounter_type in ('OUTPATIENT','INPATIENT_OBSERVATION','INPATIENT_ADMISSION'))), status varchar(255) not null check ((status in ('ACTIVE','PENDING','ON_HOLD','BILLING','COMPLETED','CANCELLED'))), primary key (id), constraint uk_visit_department unique (visit_id, department_id));
create table visit_insurances (created_at timestamp(6) not null, updated_at timestamp(6) not null, id uuid not null, patient_insurance_id uuid not null, visit_id uuid not null, primary key (id), constraint uk_visit_patient_insurance unique (visit_id, patient_insurance_id));
create table visit_pre_instruction_medications (created_at timestamp(6) not null, id uuid not null, pre_instruction_id uuid not null, quantity varchar(100), route varchar(100), dosage varchar(200), duration varchar(200), frequency varchar(200), med_name varchar(200) not null, other_instructions varchar(1000), primary key (id));
create table visit_pre_instruction_product_requests (quantity float(53), created_at timestamp(6) not null, updated_at timestamp(6) not null, id uuid not null, pre_instruction_id uuid not null, processed_by_id uuid, product_id uuid, requested_by_id uuid, status varchar(20) not null check ((status in ('PENDING','ONGOING','COMPLETED','REJECTED'))), primary key (id));
create table visit_pre_instructions (created_at timestamp(6) not null, added_by_id uuid, id uuid not null, visit_department_id uuid not null, visit_id uuid not null, type varchar(20) not null, note varchar(1000), primary key (id));
create table visit_vital_signs_groups (created_at timestamp(6) not null, added_by_id uuid, id uuid not null, visit_id uuid not null, primary key (id));
create table visits (created_at timestamp(6) not null, updated_at timestamp(6) not null, visit_date timestamp(6) not null, id uuid not null, patient_id uuid not null, status varchar(20) not null check ((status in ('CREATED','IN_PROGRESS','CANCELLED','COMPLETED'))), primary key (id));
create table vital_measurements (created_at timestamp(6) not null, group_id uuid not null, id uuid not null, unit varchar(50) not null, measurement_name varchar(100) not null, measurement_value varchar(100) not null, primary key (id));
create table worker_departments (department_id uuid not null, worker_id uuid not null, primary key (department_id, worker_id));
create table worker_roles (worker_id uuid not null, role_name varchar(255) check ((role_name in ('MANAGER','CLINIC_ADMIN','FINANCE','STAFF','RECEPTION','NURSE','CLINICIAN','ADMIN'))));
create table workers (active boolean not null, auto_reset boolean not null, date_of_birth date, expiration_date date, has_expiration boolean, issued_date date, max_active_sessions integer not null, must_change_on_next_login boolean not null, required boolean, reset_period_days integer, created_at timestamp(6) not null, last_password_change timestamp(6), next_reset_date timestamp(6), updated_at timestamp(6) not null, department_id uuid, id uuid not null, password_hash varchar(120), account_status varchar(255) not null check ((account_status in ('PENDING','ACTIVE','DISABLED'))), document_number varchar(255), document_url varchar(255), email varchar(255) unique, first_name varchar(255) not null, gender varchar(255) check ((gender in ('MALE','FEMALE','OTHER'))), issued_by varchar(255), last_name varchar(255), notes varchar(255), phone_number varchar(255) unique, profile_photo_url varchar(255), title varchar(255), type varchar(255) check ((type in ('LICENSE','DIPLOMA_CERTIFICATE','DEGREE_CERTIFICATE','TRAINING_CERTIFICATE','NATIONAL_ID','PASSPORT','BACKGROUND_CHECK','WORK_PERMIT','OTHER'))), username varchar(255) unique, primary key (id));
create index idx_consultation_answers_consultation_id on consultation_answers (consultation_id);
create index idx_consultation_answers_visit_id on consultation_answers (visit_id);
create index idx_consultation_answers_patient_id on consultation_answers (patient_id);
create index idx_department_form_versions_form_id on department_form_versions (form_id);
create index idx_department_forms_department_id on department_forms (department_id);
create index idx_department_forms_updated_at on department_forms (updated_at);
create index idx_department_insurance_department on department_insurance_policies (department_id);
create index idx_department_insurance_provider on department_insurance_policies (insurance_provider_id);
create index idx_department_profile_product_profile on department_profile_products (profile_id);
create index idx_department_profile_product_product on department_profile_products (product_id);
create index idx_department_profile_department on department_profiles (department_id);
create index idx_form_answers_form_version_id on form_answers (form_version_id);
create index idx_forms_name on forms (name);
create index idx_forms_type on forms (type);
create index idx_forms_is_deleted on forms (is_deleted);
create index idx_product_coverage_product on product_insurance_coverages (product_id);
create index idx_product_coverage_insurance on product_insurance_coverages (insurance_provider_id);
create index idx_products_name on products (name);
create index idx_products_type on products (type);
create index idx_products_code on products (code);
alter table if exists clinic_profile_contacts add constraint FKdhfwg40llosne57br6gnjlw0a foreign key (clinic_profile_id) references clinic_profiles;
alter table if exists clinic_profile_metadata add constraint FKohno1ccq9158k24v19j0s88nx foreign key (clinic_profile_id) references clinic_profiles;
alter table if exists consultation_answers add constraint FKlbrrdcpownms8l0yto8qjy766 foreign key (department_id) references departments;
alter table if exists consultation_answers add constraint FK6fo1lr96jk49div99w6yemyft foreign key (department_form_id) references department_forms;
alter table if exists consultation_answers add constraint FK4sbfc01cun0o8j7h181ikyg8i foreign key (submitted_by_worker_id) references workers;
alter table if exists department_form_versions add constraint FKclju4n6nuwxrrjlts9y7dm4cb foreign key (form_id) references department_forms;
alter table if exists department_forms add constraint FKtdxcsc1l8ulggxw81onbhhlf4 foreign key (department_id) references departments;
alter table if exists department_insurance_policies add constraint FK26bkm4ag888uy2u663jer84bu foreign key (department_id) references departments;
alter table if exists department_insurance_policies add constraint FKqyubhtvcb6c881ercwjm2thry foreign key (insurance_provider_id) references insurance_providers;
alter table if exists department_profile_products add constraint FKoqy7xs31tbjm6jokny2byqadg foreign key (product_id) references products;
alter table if exists department_profile_products add constraint FKlwwnhqqc60e7pqyoirdddxd3b foreign key (profile_id) references department_profiles;
alter table if exists department_profiles add constraint FKl8clxw100kipkyw0s58t8ioa1 foreign key (department_id) references departments;
alter table if exists department_standalone_forms add constraint FK55f4idpk2ftnxtiptccsrhu20 foreign key (department_id) references departments;
alter table if exists department_standalone_forms add constraint FKlcu0gghfgqgwhwfde03ceejrh foreign key (standalone_form_id) references forms;
alter table if exists form_answers add constraint FKb1bmienmx9bdp4jf8tmaxfbg1 foreign key (form_version_id) references form_versions;
alter table if exists form_versions add constraint FKjsugk8f29jo2k0sw4fpflwyc2 foreign key (form_id) references forms;
alter table if exists note_target_users add constraint FK95mung8xjwsudpk5kaqde4sos foreign key (worker_id) references workers;
alter table if exists note_target_users add constraint FKe1vp5efpbvirc5p90erbqwb32 foreign key (note_id) references visit_department_notes;
alter table if exists password_history add constraint FKf0bgpqcnw1xgjskd4ybbl2pnm foreign key (worker_id) references workers;
alter table if exists patient_insurances add constraint FKc0anr6yjdfjwlv51g5qsxswxr foreign key (insurance_provider_id) references insurance_providers;
alter table if exists patient_insurances add constraint FK8pgdmaquaawu5audlt6w5ei7x foreign key (patient_id) references patients;
alter table if exists product_coverage_authorization_reasons add constraint FKs5slq5h81gg5d7wy5s2ddqga1 foreign key (coverage_id) references product_insurance_coverages;
alter table if exists product_insurance_coverages add constraint FKn01r3rl4d54ssf4si0g4ibru foreign key (insurance_provider_id) references insurance_providers;
alter table if exists product_insurance_coverages add constraint FKrt38uyqst3d2698x44k4iqs7l foreign key (product_id) references products;
alter table if exists refresh_tokens add constraint FK3p7jebgoa9ox5mn9sc7g3gs0i foreign key (worker_id) references workers;
alter table if exists visit_billing_containers add constraint FKq4lohdr6bd1q2cvweto2m10mp foreign key (billing_version_id) references visit_billing_versions;
alter table if exists visit_billing_containers add constraint FK8es62o0jw3si27thd5tl4kd6k foreign key (visit_id) references visits;
alter table if exists visit_billing_items add constraint FKdkg4nwc1fm4yohg0nvee5md5x foreign key (applied_patient_insurance_id) references patient_insurances;
alter table if exists visit_billing_items add constraint FKoq5ojvxw3s9gcy8wftls2npjl foreign key (billing_version_id) references visit_billing_versions;
alter table if exists visit_billing_items add constraint FKghfuhkch8r11xwxeftyrmci9t foreign key (department_insurance_billing_id) references visit_billings;
alter table if exists visit_billing_items add constraint FK3avlmkp9axp0qfgeiisubf3bj foreign key (visit_department_product_id) references visit_department_products;
alter table if exists visit_billing_payments add constraint FKom8r0wlx9hq6dr88x2wo04w9q foreign key (billing_version_id) references visit_billing_versions;
alter table if exists visit_billing_payments add constraint FKblwch9m77k7vtyetnq1k2ysre foreign key (visit_department_billing_id) references visit_department_billings;
alter table if exists visit_billing_versions add constraint FKt2gecbrxl0xi72vu7hc6djsys foreign key (visit_id) references visits;
alter table if exists visit_billings add constraint FKr57kmtwc09iyvxe1m1imsht7d foreign key (billing_version_id) references visit_billing_versions;
alter table if exists visit_billings add constraint FKbsbqx3npo9ulpl3vgehtmgcpr foreign key (patient_insurance_id) references patient_insurances;
alter table if exists visit_billings add constraint FK2bvfquq7wpple0cye79udxqa7 foreign key (visit_department_billing_id) references visit_department_billings;
alter table if exists visit_department_billings add constraint FKcumn64vqpea6ddpsy0p0w8tjv foreign key (visit_billing_id) references visit_billing_containers;
alter table if exists visit_department_billings add constraint FKh3podunqrjxb6x55wk9d6ghw5 foreign key (visit_department_id) references visit_departments;
alter table if exists visit_department_diagnostics add constraint FK3uiyxv2qgv1nigx40ixxy6h8t foreign key (visit_department_id) references visit_departments;
alter table if exists visit_department_medications add constraint FK2s1p7w45kaflsmao9jmqoceol foreign key (visit_department_id) references visit_departments;
alter table if exists visit_department_note_viewers add constraint FKh67d92escb1pdslnbefo7k739 foreign key (note_id) references visit_department_notes;
alter table if exists visit_department_note_viewers add constraint FKejei8i6xk1006hlxo389amef6 foreign key (viewer_id) references workers;
alter table if exists visit_department_notes add constraint FKimq1xye8n9dha07a6dkh4mg4g foreign key (created_by_id) references workers;
alter table if exists visit_department_notes add constraint FKmn8sxvi8r0dn83fssjt8wt7xd foreign key (visit_department_id) references visit_departments;
alter table if exists visit_department_processors add constraint FKoocmg7bjuc5uulpcra57pux2g foreign key (worker_id) references workers;
alter table if exists visit_department_processors add constraint FK3yq983rak83f5e7b9q9k90mag foreign key (visit_department_id) references visit_departments;
alter table if exists visit_department_product_snapshots add constraint FK5duc7sgldjpuy0g9x2hmy5qie foreign key (added_by_worker_id) references workers;
alter table if exists visit_department_product_snapshots add constraint FK5g0k6ohawnbm3fweb0i4ya7ax foreign key (applied_patient_insurance_id) references patient_insurances;
alter table if exists visit_department_product_snapshots add constraint FKtesqpk9a8bfkdh3d2qvtpo4e1 foreign key (billed_by_worker_id) references workers;
alter table if exists visit_department_product_snapshots add constraint FK16i5qkwffb9f5njjdmxypb41x foreign key (billing_version_id) references visit_billing_versions;
alter table if exists visit_department_product_snapshots add constraint FK8w780payr602edatpo5e7kbm8 foreign key (product_id) references products;
alter table if exists visit_department_product_snapshots add constraint FKmhlcgw2wpu93srkmgukwsglf0 foreign key (visit_department_id) references visit_departments;
alter table if exists visit_department_products add constraint FKi5qc9aplclh2sss934r4e88mo foreign key (added_by_worker_id) references workers;
alter table if exists visit_department_products add constraint FKg2i2jvi47aw25stpurcmsdbqi foreign key (billed_by_worker_id) references workers;
alter table if exists visit_department_products add constraint FK4w2vmgqjb45yf2wa6otlcrve1 foreign key (processor_worker_id) references workers;
alter table if exists visit_department_products add constraint FKor5c3a0sgfu3nw0hpomtjfda7 foreign key (product_id) references products;
alter table if exists visit_department_products add constraint FKtiqqdj37rn6jpr64qdd7d31fn foreign key (visit_department_id) references visit_departments;
alter table if exists visit_departments add constraint FKad89eougj8341yy55upcfjkae foreign key (department_id) references departments;
alter table if exists visit_departments add constraint FK55eo36itc2ysh4mbu8hb0162s foreign key (parent_visit_department_id) references visit_departments;
alter table if exists visit_departments add constraint FKkwg65740wtypmtxhmpxd3imln foreign key (profile_id) references department_profiles;
alter table if exists visit_departments add constraint FK51u0uibc3mal37x6v2a75iljw foreign key (visit_id) references visits;
alter table if exists visit_insurances add constraint FK99x1nvep149eiu3rlaposycn8 foreign key (patient_insurance_id) references patient_insurances;
alter table if exists visit_insurances add constraint FK3b45tngq5q5e108vakunkhhw6 foreign key (visit_id) references visits;
alter table if exists visit_pre_instruction_medications add constraint FKny32y53i11lj4b5wpfqq0ju4x foreign key (pre_instruction_id) references visit_pre_instructions;
alter table if exists visit_pre_instruction_product_requests add constraint FK7vdbd4qo3jvppa7c3nq1ie50y foreign key (pre_instruction_id) references visit_pre_instructions;
alter table if exists visit_pre_instruction_product_requests add constraint FKflekjiauy3l5os6crxyvnxqi4 foreign key (processed_by_id) references workers;
alter table if exists visit_pre_instruction_product_requests add constraint FKcjgbmkiy65s8lnlkuw5w66yur foreign key (product_id) references products;
alter table if exists visit_pre_instruction_product_requests add constraint FK9xn8v783vqb4h9w08ckvvrehp foreign key (requested_by_id) references workers;
alter table if exists visit_pre_instructions add constraint FKhluc2rj4w407bjdym1uvvpc0t foreign key (added_by_id) references workers;
alter table if exists visit_pre_instructions add constraint FK8au0o6fycys1n5wfdqj2avcqq foreign key (visit_id) references visits;
alter table if exists visit_pre_instructions add constraint FKn2bp9ld9e4189thm7sfj71vf4 foreign key (visit_department_id) references visit_departments;
alter table if exists visit_vital_signs_groups add constraint FKogcvp58bxdxbp7y57bcrhee42 foreign key (added_by_id) references workers;
alter table if exists visit_vital_signs_groups add constraint FKsdovtmsxfhnonm5ymou64hp9h foreign key (visit_id) references visits;
alter table if exists visits add constraint FKra5p2e0tp6djolm46kdr42cyt foreign key (patient_id) references patients;
alter table if exists vital_measurements add constraint FKbnpo3ep7tsyp402la19jreq7 foreign key (group_id) references visit_vital_signs_groups;
alter table if exists worker_departments add constraint FKkhsxgdpm0mmqlx0o1g3lkk1hp foreign key (department_id) references departments;
alter table if exists worker_departments add constraint FK6xv08bki1ku42o1hvfpdmgut8 foreign key (worker_id) references workers;
alter table if exists worker_roles add constraint FKkroh9p6ey1iv97iokqm3jq7p1 foreign key (worker_id) references workers;
alter table if exists workers add constraint FK67cxua9avhupaydliqqatgl37 foreign key (department_id) references departments;
